# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    nmap \
    gobuster \
    ffuf \
    sqlmap \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . .

# Install Poetry
RUN pip install poetry

# Install Python dependencies
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-root

# Copy environment variables example
COPY .env.example .env

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "ui/streamlit_app.py"]