# Makefile for common tasks

install:
    poetry install

test:
    poetry run pytest tests/

lint:
    poetry run black .
    poetry run isort .
    poetry run flake8 .

build-docker:
    docker build -t cybersecurity-agent-pinewheel .

run-docker:
    docker run -p 8501:8501 cybersecurity-agent-pinewheel

clean:
    rm -rf __pycache__ .pytest_cache